"""initial recruitflow schema

Revision ID: d2e439e15d77
Revises: 
Create Date: 2026-07-26 15:48:22.603149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2e439e15d77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sync_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sink_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_version', sa.SmallInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('external_record_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_sync_due', 'document_sync_jobs', ['status', 'next_retry_at', 'created_at'], unique=False)
    op.create_index('ix_sync_entity', 'document_sync_jobs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_conversations_user_time', 'agent_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_request', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_target', 'audit_logs', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_index('ix_audit_user_time', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('current_company', sa.String(length=150), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('work_experience', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_candidates_name', 'candidates', ['name'], unique=False)
    op.create_index('ix_candidates_source_deleted', 'candidates', ['source', 'deleted_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_code', sa.String(length=40), nullable=False),
    sa.Column('job_name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code')
    )
    op.create_index('ix_jobs_department', 'jobs', ['department'], unique=False)
    op.create_index('ix_jobs_status_owner', 'jobs', ['status', 'owner_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_messages_conversation_time', 'agent_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_agent_messages_request', 'agent_messages', ['request_id'], unique=False)
    op.create_table('candidate_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=False),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uk_candidate_jobs_candidate_job')
    )
    op.create_index('ix_candidate_jobs_job_status', 'candidate_jobs', ['job_id', 'status'], unique=False)
    op.create_index('ix_candidate_jobs_owner_next', 'candidate_jobs', ['owner_id', 'next_action_at'], unique=False)
    op.create_index('ix_candidate_jobs_stage_time', 'candidate_jobs', ['status', 'stage_entered_at'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('corrected_data', sa.JSON(), nullable=True),
    sa.Column('parse_status', sa.String(length=30), nullable=False),
    sa.Column('parser_model', sa.String(length=100), nullable=True),
    sa.Column('parser_error_code', sa.String(length=80), nullable=True),
    sa.Column('parser_error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_sha256')
    )
    op.create_index('ix_resumes_candidate', 'resumes', ['candidate_id'], unique=False)
    op.create_index('ix_resumes_status_created', 'resumes', ['parse_status', 'created_at'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_job_id', sa.String(length=36), nullable=True),
    sa.Column('inbound_event_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=80), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_job_id'], ['candidate_jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_communications_application', 'communications', ['candidate_job_id'], unique=False)
    op.create_index('ix_communications_candidate_time', 'communications', ['candidate_id', 'occurred_at'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_job_id', sa.String(length=36), nullable=False),
    sa.Column('round', sa.String(length=20), nullable=False),
    sa.Column('interview_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('interviewer_id', sa.String(length=36), nullable=False),
    sa.Column('additional_interviewers', sa.JSON(), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('feedback_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_job_id'], ['candidate_jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviews_candidate_job', 'interviews', ['candidate_job_id', 'scheduled_at'], unique=False)
    op.create_index('ix_interviews_interviewer_time', 'interviews', ['interviewer_id', 'scheduled_at'], unique=False)
    op.create_index('ix_interviews_status_time', 'interviews', ['status', 'scheduled_at'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_job_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('interview_id', sa.String(length=36), nullable=True),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('proposed_action', sa.String(length=80), nullable=False),
    sa.Column('proposed_data', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('target_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_type', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('graph_thread_id', sa.String(length=36), nullable=True),
    sa.Column('graph_checkpoint_ns', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_job_id'], ['candidate_jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_approvals_application', 'approval_requests', ['candidate_job_id'], unique=False)
    op.create_index('ix_approvals_status_created', 'approval_requests', ['status', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_job_id', sa.String(length=36), nullable=True),
    sa.Column('interview_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_job_id'], ['candidate_jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_due', 'notifications', ['status', 'scheduled_at', 'next_retry_at'], unique=False)
    op.create_index('ix_notifications_interview', 'notifications', ['interview_id'], unique=False)
    op.create_table('inbound_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_event_id', sa.String(length=128), nullable=False),
    sa.Column('sender_external_id', sa.String(length=128), nullable=True),
    sa.Column('room_external_id', sa.String(length=128), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('relevance', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('approval_request_id', sa.String(length=36), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_event_id', name='uk_inbound_source_event')
    )
    op.create_index('ix_inbound_room_time', 'inbound_events', ['room_external_id', 'occurred_at'], unique=False)
    op.create_index('ix_inbound_status_created', 'inbound_events', ['processing_status', 'created_at'], unique=False)
    op.create_table('candidate_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_job_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('approval_request_id', sa.String(length=36), nullable=True),
    sa.Column('inbound_event_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_job_id'], ['candidate_jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inbound_event_id'], ['inbound_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_status_history_application_time', 'candidate_status_history', ['candidate_job_id', 'created_at'], unique=False)
    op.create_index('ix_status_history_request', 'candidate_status_history', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL may reuse a declared index to support a foreign key. Dropping those
    # indexes individually can therefore fail with error 1553. Dropping the
    # dependent tables in reverse creation order removes their indexes safely.
    op.drop_table('candidate_status_history')
    op.drop_table('inbound_events')
    op.drop_table('notifications')
    op.drop_table('approval_requests')
    op.drop_table('interviews')
    op.drop_table('communications')
    op.drop_table('resumes')
    op.drop_table('candidate_jobs')
    op.drop_table('agent_messages')
    op.drop_table('jobs')
    op.drop_table('candidates')
    op.drop_table('audit_logs')
    op.drop_table('agent_conversations')
    op.drop_table('users')
    op.drop_table('document_sync_jobs')
